### ISSUE TITLE
AssertionError: is_incremental must always be specified!

### ISSUE THREAD

**Issue by lvhuanhuan123** [LTTM/IL-SemSegm#1]
Hello, please tell me how to solve the above problem, I want to communicate with you, thank you. 
cuda 10.0
tensorflow=1.12.0

**Comment by umbertomichieli** [comment]
Hi, you are receiving this error because you forgot to specify the 'is_incremental' parameter.
For example, run the following (under Linux) to run a first training on 19 classes followed by the finetuning approach on the last class:

python -u train_with_distillation.py \
--batch_size 4 \
--training_steps 20000 \
--start_decay_step 0 \
--validation_batch_size 1449 \
--logging_steps_interval 100 \
--validation_steps_interval 1000 \
--save_steps_interval 1000 \
--decay_steps 20000 \
--start_learning_rate 1e-4 \
--end_learning_rate 1e-6 \
--training_file ../../../sample_dataset/tfrecords/train_1_19.tfrecords \
--validation_file ../../../sample_dataset/tfrecords/val_1_19.tfrecords \
--up_to_class 19 \
--lambda_distillation 0 \
--is_incremental 0 \
--is_save_new_softmax_maps 0 \
&> output_1_19.txt

python run_generate_old_maps.py \
--load_model 1_to_19 \ 
--validation_file ../../../sample_dataset/tfrecords/train_20.tfrecords

python -u train_with_distillation.py \
--batch_size 4 \
--training_steps 21000 \
--start_decay_step 20000 \
--validation_batch_size 1449 \
--logging_steps_interval 100 \
--validation_steps_interval 1000 \
--save_steps_interval 1000 \
--decay_steps 20000 \
--start_learning_rate 5e-5 \
--end_learning_rate 1e-6 \
--load_model 1_to_19 \
--training_file ../../../sample_dataset/tfrecords/train_20.tfrecords \
--validation_file ../../../sample_dataset/tfrecords/val_1_20.tfrecords \
--from_new_class 20 \
--to_new_class 20 \
--standard_loss_applied_to all \
--distill_loss_applied_to old_bgr \
--lambda_distillation 0 \
--is_incremental 1 \
--is_save_new_softmax_maps 0 \
&> output_1_19_20_nodist.txt



The same commands in Windows batch:
call python -u train_with_distillation.py ^
--batch_size 4 ^
--training_steps 20000 ^
--start_decay_step 0 ^
--validation_batch_size 1449 ^
--logging_steps_interval 100 ^
--validation_steps_interval 1000 ^
--save_steps_interval 1000 ^
--decay_steps 20000 ^
--start_learning_rate 1e-4 ^
--end_learning_rate 1e-6 ^
--training_file ../../sample_dataset/tfrecords/train_1_19.tfrecords ^
--validation_file ../../sample_dataset/tfrecords/val_1_19.tfrecords ^
--up_to_class 19 ^
--lambda_distillation 0 ^
--is_incremental 0 ^
--is_save_new_softmax_maps 0 ^
1> output_1_19.txt 2>&1

call python run_generate_old_maps.py ^
--load_model 1_to_19 ^
--validation_file ../../sample_dataset/tfrecords/train_20.tfrecords

call python -u train_with_distillation.py ^
--batch_size 4 ^
--training_steps 21000 ^
--start_decay_step 20000 ^
--validation_batch_size 1449 ^
--logging_steps_interval 100 ^
--validation_steps_interval 1000 ^
--save_steps_interval 1000 ^
--decay_steps 20000 ^
--start_learning_rate 5e-5 ^
--end_learning_rate 1e-6 ^
--load_model 1_to_19 ^
--training_file ../../sample_dataset/tfrecords/train_20.tfrecords ^
--validation_file ../../sample_dataset/tfrecords/val_1_20.tfrecords ^
--from_new_class 20 ^
--to_new_class 20 ^
--standard_loss_applied_to all ^
--distill_loss_applied_to old_bgr ^
--lambda_distillation 0 ^
--is_incremental 1 ^
--is_save_new_softmax_maps 0 ^
1> output_1_19_20_nodist.txt 2>&1


You can check this on the README files or looking at the script.job and script.bat files.

**Comment by lvhuanhuan123** [comment]
UnboundLocalError: local variable 'G_final_loss_value' referenced before assignment

First, thank you very much for your reply. I now have a new problem. 
I think it should be because 188 in LD1 / train_with_distillation.py has become a local variable by default, but I tried to change G_final_loss_value to a global variable, and still couldn't solve this problem. 
I hope to get your guidance and wish you a happy life.

**Comment by umbertomichieli** [comment]
Hi, it's hard to tell without knowing further details.
Have you downloaded the dataset (tfrecords files) and placed them in the correct folder ("../../sample_dataset/tfrecords/" with respect to the main file)?
Which line is throwing the error you mentioned?

**Comment by Qy19970630** [comment]
I also encountered the same error, did you solve it？

**Comment by QianSiWang1** [comment]
I also encountered the same problem“UnboundLocalError: local variable 'G_final_loss_value' referenced before assignment”, did you solve it？

**Comment by QianSiWang1** [comment]
Following the error message, I noticed that the  ‘’--training_file‘’ in the ''script.job'' should be "../../sample_dataset/" instead of "../../../sample_dataset". And then it works!

**Comment by umbertomichieli** [comment]
Hi, I was about to debug the issue. 
Thank you, you saved me some time. 
I fixed it.
